runtime: nodejs22

instance_class: F1

env: standard

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  min_instances: 0
  max_instances: 2

env_variables:
  NODE_ENV: production

# VPC Connector for Cloud SQL (uncomment when VPC connector is created)
# vpc_access_connector:
#   name: projects/client-info-felipe-2025/locations/europe-west1/connectors/serverless-vpc
